export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_ATTRIBUTES = 'FETCH_PRODUCT_ATTRIBUTES';
export const FETCH_PRODUCT_REVIEWS = 'FETCH_PRODUCT_REVIEWS';
